variables:
  DEBIAN_FRONTEND: noninteractive

stages:
  - test
  - build-website

before_script:
         - DEBIAN_FRONTEND=noninteractive apt-get update
         - DEBIAN_FRONTEND=noninteractive apt-get -y --force-yes install curl wget apt-transport-https software-properties-common ca-certificates gnupg
         - curl -fSsL https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor | tee /usr/share/keyrings/google-chrome.gpg > /dev/null
         - echo deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main | tee /etc/apt/sources.list.d/google-chrome.list
         - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --yes --dearmor --output /usr/share/keyrings/microsoft.gpg
         - sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/microsoft-debian-bullseye-prod bullseye main" > /etc/apt/sources.list.d/microsoft.list'
         - apt update && apt install -y powershell google-chrome-stable
         - mkdir -p /etc/apt/keyrings
         - curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
         - NODE_MAJOR=20
         - echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
         - apt-get update
         - apt-get install nodejs -y

test:
     tags:
         - Ubuntu2004-64bit
     stage: test
     script:
         - cd /builds/mgeilen/model-image
         - cd module/model-image
         - npm install
         - npm run build
         - npm link
         - cd ../../processor
         - npm install
         - npm link model-image
         - npm run test
